name: Sandbox

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "**.md"

permissions:
  contents: read
  id-token: write

jobs:
  run_go_tests:
    name: "Go: Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '^1.25'

      - name: Configure Datadog Test Optimization
        uses: datadog/test-visibility-github-action@v2.4.1
        with:
          api_key: ${{ secrets.DATADOG_API_KEY }}
          languages: go
          service: istio-test

      - name: Run tests
        run: go test ./...

  build_and_push_us:
    name: "Sandbox Registry: us-docker.pkg.dev"
    uses: osinfra-io/github-misc-called-workflows/.github/workflows/build-and-push.yml@v0.2.2
    if: github.actor != 'dependabot[bot]'
    needs: run_go_tests
    with:
      cache_from: type=gha
      cache_to: type=gha,mode=max
      build_args: |
            DD_GIT_REPOSITORY_URL=https://github.com/${{ github.repository }}
            DD_GIT_COMMIT_SHA=${{ github.sha }}
      registry: us-docker.pkg.dev
      service_account: plt-istio-test-github@plt-lz-backend-tf69-sb.iam.gserviceaccount.com
      tags: us-docker.pkg.dev/plt-lz-services-tf7f-sb/plt-docker-standard/istio-test:${{ github.sha }}
      workload_identity_provider: projects/746490462722/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
